import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  typedocSidebar: [
    {
      type: "autogenerated",
      dirName: "api"
    },
  ],
  guideSidebar: [
    {
      type: "doc",
      id: "guide/introduction",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        "guide/getting-started/start-from-example",
        "guide/getting-started/setup-project",
        "guide/getting-started/declare-module",
        "guide/getting-started/first-command",
        "guide/getting-started/listening-event",
      ],
    },
    {
      type: "category",
      label: "Commands",
      items: [
        {
          type: "autogenerated",
          dirName: "guide/commands",
        },
      ],
    }
    // {
    //   type: "category",
    //   label: "Commands",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "guide/commands",
    //     },
    //   ],
    // },
  ],
};

export default sidebars;
