import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  typedocSidebar: [
    {
      type: "autogenerated",
      dirName: "api"
    },
  ],
  guideSidebar: [
    {
      type: "doc",
      id: "guide/introduction",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        "guide/getting-started/start-from-example",
        "guide/getting-started/setup-project",
        "guide/getting-started/first-command",
        "guide/getting-started/listening-event",
        "guide/getting-started/declare-module",
        "guide/music"
      ],
    },
    {
      type: "category",
      label: "Commands",
      items: [
        "guide/commands/middlewares",
        "guide/commands/subcommand",
        "guide/commands/decorators",
        "guide/commands/options",
        "guide/commands/command-class",
      ],
    }
  ],
};

export default sidebars;
